In [1]:
from sklearn import datasets

import pandas as pd
import numpy as np

iris = datasets.load_iris()


In [2]:
print(iris.keys())


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
X = iris.data

df = pd.DataFrame(X, columns = iris.feature_names)
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [4]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 6)

X = iris.data
y = iris.target

knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [5]:
X_new = np.array([[5.6, 2.8, 3.9, 1.1],
                 [5.7, 2.6, 3.8, 1.3],
                 [4.7, 3.2, 1.3, 0.2]])

prediction = knn.predict(X_new)

In [19]:
y = 0

for i in X_new:
    print (i , ' ', prediction[ y ] )
    y += 1

[5.6 2.8 3.9 1.1]   1
[5.7 2.6 3.8 1.3]   1
[4.7 3.2 1.3 0.2]   0
